engineStrict: true

gitBranchLockfile: true

mergeGitBranchLockfilesBranchPattern:
  - main
  - release*

onlyBuiltDependencies:
  - esbuild
  - sharp

shellEmulator: true

verifyDepsBeforeRun: install
